"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4x)djnt-g2pl&*#4i$1zh8*%vfy=3%@+48xc^npm*%4i66gin!'

# IP Whitelist Management Secret Key
# This key is required to add/remove IPs from whitelist via API
IP_WHITELIST_SECRET_KEY = 'your-super-secret-whitelist-key-change-this-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold - must be before django.contrib.admin
    'unfold.contrib.filters',  # Optional filters
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt',  # JWT Authentication
    'corsheaders',
    'drf_spectacular',  # API Documentation
    
    # Local Apps
    'frauddetect',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'frauddetect.login_middleware.LoginSecurityMiddleware',  # 🛡️ Login Security
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================
# INTERNATIONALIZATION
# ============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True

# ============================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise configuration for production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ============================================
# MEDIA FILES (User Uploaded Files)
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# REST FRAMEWORK CONFIGURATION
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================
# DRF SPECTACULAR (Swagger/ReDoc) CONFIGURATION
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Fraud Detection API',
    'DESCRIPTION': 'API for fraud detection system with device fingerprinting, transaction monitoring, and risk assessment',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Devices', 'description': 'Device management and fingerprinting'},
        {'name': 'Login Events', 'description': 'Login history and suspicious activity tracking'},
        {'name': 'Transactions', 'description': 'Transaction processing with fraud detection'},
        {'name': 'Fraud Events', 'description': 'Fraud event management and resolution'},
        {'name': 'Risk Profiles', 'description': 'User risk assessment and profiling'},
        {'name': 'System Logs', 'description': 'System activity logs'},
        {'name': 'IP Blocklist', 'description': 'IP address blocking management'},
        {'name': 'Dashboard', 'description': 'Dashboard statistics and analytics'},
    ],
}

# ============================================
# CORS SETTINGS
# ============================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# ============================================
# 🔥 FRAUD DETECTION SETTINGS
# ============================================
FRAUD_SETTINGS = {
    'MAX_LOGIN_ATTEMPTS': 5,              # সর্বোচ্চ লগইন চেষ্টা
    'LOGIN_ATTEMPT_WINDOW': 300,          # ৫ মিনিট
    'HIGH_AMOUNT_THRESHOLD': 100000,      # ১ লাখ টাকার বেশি = সন্দেহজনক
    'BUSINESS_HOURS_START': 8,            # সকাল ৮টা
    'BUSINESS_HOURS_END': 18,             # সন্ধ্যা ৬টা
    'MAX_DAILY_TRANSACTIONS': 50,         # দৈনিক সর্বোচ্চ ট্রানজেকশন
    'MAX_TRANSACTION_AMOUNT_DAILY': 500000,
    'VELOCITY_CHECK_WINDOW': 3600,        # ১ ঘণ্টা
    'MAX_TRANSACTIONS_PER_HOUR': 10,      # ঘণ্টায় সর্বোচ্চ ১০টি
}

# ============================================
# 🌍 GEO-RESTRICTION SETTINGS (KSA Compliance)
# ============================================
# IMPORTANT: For Saudi Arabia data residency compliance
# Only allow access from specific countries

# Enable geo-restriction (set to False to disable)
GEO_RESTRICTION_ENABLED = True

# Allowed countries for access (ISO 3166-1 alpha-2 codes)
# Primary: Saudi Arabia (SA)
# Can add more countries as needed
ALLOWED_COUNTRIES = [
    'SA',  # Saudi Arabia (Primary)
    # Add more countries here if needed in the future:
    # 'AE',  # United Arab Emirates
    # 'KW',  # Kuwait
    # 'QA',  # Qatar
    # 'BH',  # Bahrain
    # 'OM',  # Oman
    # 'BD',
]

# Action when access from non-allowed country
# Options: 'block' (deny access), 'flag' (allow but mark suspicious)
GEO_RESTRICTION_ACTION = 'block'  # Strict mode for KSA compliance

# Automatically add non-allowed country IPs to blocklist
# When enabled, IPs from non-allowed countries are permanently blocked
AUTO_BLOCK_NON_ALLOWED_COUNTRY_IPS = True

# Whitelist IPs (bypass geo-restriction)
# Useful for admin access, testing, or specific trusted IPs
GEO_RESTRICTION_WHITELIST_IPS = [
    # '203.0.113.50',  # Example: Office IP
    # '198.51.100.0/24',  # Example: Office network
]

# Device trust based on country
# Devices from allowed countries are automatically trusted
AUTO_TRUST_DEVICES_FROM_ALLOWED_COUNTRIES = True

# Block devices from non-allowed countries
AUTO_BLOCK_DEVICES_FROM_BLOCKED_COUNTRIES = True

# ============================================
# 🌍 COUNTRY RISK LEVELS (SIMPLIFIED)
# ============================================
# Simple binary approach: Only ALLOWED_COUNTRIES are safe
# All other countries are considered high-risk and will be blocked
# No need for separate HIGH/MEDIUM/LOW risk categories

# ============================================
# 🎨 DJANGO UNFOLD CONFIGURATION
# ============================================
UNFOLD = {
    "SITE_TITLE": "Fraud Detection System",
    "SITE_HEADER": "Fraud Detection Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "🛡️",  # Icon for light mode
        "dark": lambda request: "🛡️",   # Icon for dark mode
    },
    "SITE_LOGO": None,
    "SITE_SYMBOL": "shield",  # Symbol from icon set
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "frauddetect.admin.environment_callback",
    "DASHBOARD_CALLBACK": "frauddetect.admin.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Security & Monitoring",
                "separator": True,
                "items": [
                    {
                        "title": "Devices",
                        "icon": "devices",
                        "link": "/admin/frauddetect/device/",
                    },
                    {
                        "title": "Login Events",
                        "icon": "login",
                        "link": "/admin/frauddetect/loginevent/",
                    },
                    {
                        "title": "IP Blocklist",
                        "icon": "block",
                        "link": "/admin/frauddetect/ipblocklist/",
                    },
                ],
            },
            {
                "title": "Transactions & Fraud",
                "separator": True,
                "items": [
                    {
                        "title": "Transactions",
                        "icon": "payments",
                        "link": "/admin/frauddetect/transaction/",
                    },
                    {
                        "title": "Fraud Events",
                        "icon": "warning",
                        "link": "/admin/frauddetect/fraudevent/",
                    },
                    {
                        "title": "Risk Profiles",
                        "icon": "assessment",
                        "link": "/admin/frauddetect/riskprofile/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "items": [
                    {
                        "title": "System Logs",
                        "icon": "description",
                        "link": "/admin/frauddetect/systemlog/",
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                ],
            },
        ],
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# ============================================
# SIMPLE JWT CONFIGURATION
# ============================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

# ============================================
# AUTHENTICATION CONFIGURATION
# ============================================
# Using custom JWT authentication with fraud detection
# No allauth or dj-rest-auth needed
