# Generated by Django 5.2.8 on 2025-12-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Production Config', 'Test Config')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('is_active', models.BooleanField(default=False, help_text='Only one config can be active at a time')),
                ('geo_restriction_enabled', models.BooleanField(default=True, help_text='Enable geographic restriction')),
                ('allowed_countries', models.JSONField(default=list, help_text="List of allowed country codes (e.g., ['SA', 'AE'])")),
                ('auto_block_non_allowed_ips', models.BooleanField(default=True, help_text='Automatically block IPs from non-allowed countries')),
                ('auto_trust_devices_from_allowed_countries', models.BooleanField(default=True, help_text='Automatically trust devices from allowed countries')),
                ('auto_block_devices_from_blocked_countries', models.BooleanField(default=True, help_text='Automatically block devices from non-allowed countries')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Maximum login attempts before blocking')),
                ('login_attempt_window_minutes', models.IntegerField(default=5, help_text='Time window for login attempts (in minutes)')),
                ('require_trusted_device', models.BooleanField(default=True, help_text='Only allow login from trusted devices')),
                ('high_amount_threshold', models.DecimalField(decimal_places=2, default=100000, help_text='Amount above this is considered high-risk (in SAR)', max_digits=15)),
                ('max_daily_transactions', models.IntegerField(default=50, help_text='Maximum transactions per day per user')),
                ('max_transaction_amount_daily', models.DecimalField(decimal_places=2, default=500000, help_text='Maximum total transaction amount per day (in SAR)', max_digits=15)),
                ('max_transactions_per_hour', models.IntegerField(default=10, help_text='Maximum transactions per hour per user')),
                ('business_hours_start', models.IntegerField(default=8, help_text='Business hours start (0-23)')),
                ('business_hours_end', models.IntegerField(default=18, help_text='Business hours end (0-23)')),
                ('flag_outside_business_hours', models.BooleanField(default=True, help_text='Flag transactions outside business hours as suspicious')),
                ('risk_score_threshold_low', models.IntegerField(default=20, help_text='Risk score below this is considered low risk')),
                ('risk_score_threshold_medium', models.IntegerField(default=40, help_text='Risk score below this is considered medium risk')),
                ('risk_score_threshold_high', models.IntegerField(default=70, help_text='Risk score above this is considered high risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Configuration',
                'verbose_name_plural': 'Fraud Configurations',
                'db_table': 'fraud_configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
