# Generated by Django 5.2.8 on 2025-12-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetect', '0002_fraudconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_whitelisted',
            field=models.BooleanField(default=False, help_text='Whitelisted devices bypass all fraud checks'),
        ),
        migrations.AddField(
            model_name='device',
            name='whitelist_reason',
            field=models.CharField(blank=True, help_text='Reason for whitelisting', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='whitelisted_at',
            field=models.DateTimeField(blank=True, help_text='When this device was whitelisted', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='whitelisted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who whitelisted this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudconfig',
            name='quick_whitelist_ips',
            field=models.JSONField(blank=True, default=list, help_text="Quick IP whitelist (e.g., ['127.0.0.1', '192.168.1.100']). For detailed management, use IPWhitelist model."),
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to whitelist', unique=True)),
                ('description', models.CharField(blank=True, help_text="Purpose of this IP (e.g., 'Office IP', 'Admin Home')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this whitelist entry')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for temporary whitelist', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this IP was used', null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Whitelist',
                'verbose_name_plural': 'IP Whitelist',
                'db_table': 'ip_whitelist',
                'ordering': ['-added_at'],
            },
        ),
    ]
