# Generated by Django 5.2.8 on 2025-12-07 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetect', '0003_device_is_whitelisted_device_whitelist_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_reasons',
            field=models.JSONField(default=list, help_text='List of reasons for risk score'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Bank Transfer'), ('p2p', 'Peer-to-Peer'), ('international', 'International Transfer'), ('cash_withdrawal', 'Cash Withdrawal'), ('bill_payment', 'Bill Payment'), ('purchase', 'Purchase'), ('crypto', 'Cryptocurrency'), ('deposit', 'Deposit'), ('other', 'Other')], default='transfer', help_text='Type of transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='triggered_patterns',
            field=models.JSONField(default=list, help_text='List of pattern IDs that triggered'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_suspicious'], name='transaction_is_susp_f63ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['requires_manual_review'], name='transaction_require_11a5b3_idx'),
        ),
    ]
