# Generated by Django 5.2.8 on 2025-12-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetect', '0004_transaction_city_transaction_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='whitelist_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='whitelisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='whitelisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='allowed_countries',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='auto_block_devices_from_blocked_countries',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='auto_block_non_allowed_ips',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='auto_trust_devices_from_allowed_countries',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='business_hours_end',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='business_hours_start',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='flag_outside_business_hours',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='geo_restriction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='high_amount_threshold',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='login_attempt_window_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='max_daily_transactions',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='max_transaction_amount_daily',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='max_transactions_per_hour',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='quick_whitelist_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='require_trusted_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='risk_score_threshold_high',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='risk_score_threshold_low',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='fraudconfig',
            name='risk_score_threshold_medium',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Bank Transfer'), ('p2p', 'Peer-to-Peer'), ('international', 'International Transfer'), ('cash_withdrawal', 'Cash Withdrawal'), ('bill_payment', 'Bill Payment'), ('purchase', 'Purchase'), ('crypto', 'Cryptocurrency'), ('deposit', 'Deposit'), ('other', 'Other')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='triggered_patterns',
            field=models.JSONField(default=list),
        ),
    ]
